/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuccessPageRouteImport } from './routes/success-page'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PaymentDetailsRouteImport } from './routes/payment-details'
import { Route as MyBookingRouteImport } from './routes/my-booking'
import { Route as FutureAppointmentSuccesRouteImport } from './routes/future-appointment-succes'
import { Route as FutureAppointmentPendingRouteImport } from './routes/future-appointment-pending'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as dashboardLayoutRouteImport } from './routes/(dashboard)/_layout'
import { Route as DoctorsDoctorIdDetailsRouteImport } from './routes/doctors.$doctorId.details'
import { Route as DoctorsDoctorIdBookingRouteImport } from './routes/doctors.$doctorId.booking'
import { Route as dashboardLayoutDashboardRouteImport } from './routes/(dashboard)/_layout/dashboard'

const SuccessPageRoute = SuccessPageRouteImport.update({
  id: '/success-page',
  path: '/success-page',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentDetailsRoute = PaymentDetailsRouteImport.update({
  id: '/payment-details',
  path: '/payment-details',
  getParentRoute: () => rootRouteImport,
} as any)
const MyBookingRoute = MyBookingRouteImport.update({
  id: '/my-booking',
  path: '/my-booking',
  getParentRoute: () => rootRouteImport,
} as any)
const FutureAppointmentSuccesRoute = FutureAppointmentSuccesRouteImport.update({
  id: '/future-appointment-succes',
  path: '/future-appointment-succes',
  getParentRoute: () => rootRouteImport,
} as any)
const FutureAppointmentPendingRoute =
  FutureAppointmentPendingRouteImport.update({
    id: '/future-appointment-pending',
    path: '/future-appointment-pending',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardLayoutRoute = dashboardLayoutRouteImport.update({
  id: '/(dashboard)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsDoctorIdDetailsRoute = DoctorsDoctorIdDetailsRouteImport.update({
  id: '/doctors/$doctorId/details',
  path: '/doctors/$doctorId/details',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsDoctorIdBookingRoute = DoctorsDoctorIdBookingRouteImport.update({
  id: '/doctors/$doctorId/booking',
  path: '/doctors/$doctorId/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardLayoutDashboardRoute =
  dashboardLayoutDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => dashboardLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/future-appointment-pending': typeof FutureAppointmentPendingRoute
  '/future-appointment-succes': typeof FutureAppointmentSuccesRoute
  '/my-booking': typeof MyBookingRoute
  '/payment-details': typeof PaymentDetailsRoute
  '/search': typeof SearchRoute
  '/success-page': typeof SuccessPageRoute
  '/auth/login': typeof AuthLoginRoute
  '/dashboard': typeof dashboardLayoutDashboardRoute
  '/doctors/$doctorId/booking': typeof DoctorsDoctorIdBookingRoute
  '/doctors/$doctorId/details': typeof DoctorsDoctorIdDetailsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/future-appointment-pending': typeof FutureAppointmentPendingRoute
  '/future-appointment-succes': typeof FutureAppointmentSuccesRoute
  '/my-booking': typeof MyBookingRoute
  '/payment-details': typeof PaymentDetailsRoute
  '/search': typeof SearchRoute
  '/success-page': typeof SuccessPageRoute
  '/auth/login': typeof AuthLoginRoute
  '/dashboard': typeof dashboardLayoutDashboardRoute
  '/doctors/$doctorId/booking': typeof DoctorsDoctorIdBookingRoute
  '/doctors/$doctorId/details': typeof DoctorsDoctorIdDetailsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/future-appointment-pending': typeof FutureAppointmentPendingRoute
  '/future-appointment-succes': typeof FutureAppointmentSuccesRoute
  '/my-booking': typeof MyBookingRoute
  '/payment-details': typeof PaymentDetailsRoute
  '/search': typeof SearchRoute
  '/success-page': typeof SuccessPageRoute
  '/(dashboard)/_layout': typeof dashboardLayoutRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/(dashboard)/_layout/dashboard': typeof dashboardLayoutDashboardRoute
  '/doctors/$doctorId/booking': typeof DoctorsDoctorIdBookingRoute
  '/doctors/$doctorId/details': typeof DoctorsDoctorIdDetailsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/future-appointment-pending'
    | '/future-appointment-succes'
    | '/my-booking'
    | '/payment-details'
    | '/search'
    | '/success-page'
    | '/auth/login'
    | '/dashboard'
    | '/doctors/$doctorId/booking'
    | '/doctors/$doctorId/details'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/future-appointment-pending'
    | '/future-appointment-succes'
    | '/my-booking'
    | '/payment-details'
    | '/search'
    | '/success-page'
    | '/auth/login'
    | '/dashboard'
    | '/doctors/$doctorId/booking'
    | '/doctors/$doctorId/details'
  id:
    | '__root__'
    | '/'
    | '/future-appointment-pending'
    | '/future-appointment-succes'
    | '/my-booking'
    | '/payment-details'
    | '/search'
    | '/success-page'
    | '/(dashboard)/_layout'
    | '/auth/login'
    | '/(dashboard)/_layout/dashboard'
    | '/doctors/$doctorId/booking'
    | '/doctors/$doctorId/details'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FutureAppointmentPendingRoute: typeof FutureAppointmentPendingRoute
  FutureAppointmentSuccesRoute: typeof FutureAppointmentSuccesRoute
  MyBookingRoute: typeof MyBookingRoute
  PaymentDetailsRoute: typeof PaymentDetailsRoute
  SearchRoute: typeof SearchRoute
  SuccessPageRoute: typeof SuccessPageRoute
  dashboardLayoutRoute: typeof dashboardLayoutRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  DoctorsDoctorIdBookingRoute: typeof DoctorsDoctorIdBookingRoute
  DoctorsDoctorIdDetailsRoute: typeof DoctorsDoctorIdDetailsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/success-page': {
      id: '/success-page'
      path: '/success-page'
      fullPath: '/success-page'
      preLoaderRoute: typeof SuccessPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-details': {
      id: '/payment-details'
      path: '/payment-details'
      fullPath: '/payment-details'
      preLoaderRoute: typeof PaymentDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-booking': {
      id: '/my-booking'
      path: '/my-booking'
      fullPath: '/my-booking'
      preLoaderRoute: typeof MyBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/future-appointment-succes': {
      id: '/future-appointment-succes'
      path: '/future-appointment-succes'
      fullPath: '/future-appointment-succes'
      preLoaderRoute: typeof FutureAppointmentSuccesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/future-appointment-pending': {
      id: '/future-appointment-pending'
      path: '/future-appointment-pending'
      fullPath: '/future-appointment-pending'
      preLoaderRoute: typeof FutureAppointmentPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/_layout': {
      id: '/(dashboard)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof dashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors/$doctorId/details': {
      id: '/doctors/$doctorId/details'
      path: '/doctors/$doctorId/details'
      fullPath: '/doctors/$doctorId/details'
      preLoaderRoute: typeof DoctorsDoctorIdDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors/$doctorId/booking': {
      id: '/doctors/$doctorId/booking'
      path: '/doctors/$doctorId/booking'
      fullPath: '/doctors/$doctorId/booking'
      preLoaderRoute: typeof DoctorsDoctorIdBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/_layout/dashboard': {
      id: '/(dashboard)/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof dashboardLayoutDashboardRouteImport
      parentRoute: typeof dashboardLayoutRoute
    }
  }
}

interface dashboardLayoutRouteChildren {
  dashboardLayoutDashboardRoute: typeof dashboardLayoutDashboardRoute
}

const dashboardLayoutRouteChildren: dashboardLayoutRouteChildren = {
  dashboardLayoutDashboardRoute: dashboardLayoutDashboardRoute,
}

const dashboardLayoutRouteWithChildren = dashboardLayoutRoute._addFileChildren(
  dashboardLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FutureAppointmentPendingRoute: FutureAppointmentPendingRoute,
  FutureAppointmentSuccesRoute: FutureAppointmentSuccesRoute,
  MyBookingRoute: MyBookingRoute,
  PaymentDetailsRoute: PaymentDetailsRoute,
  SearchRoute: SearchRoute,
  SuccessPageRoute: SuccessPageRoute,
  dashboardLayoutRoute: dashboardLayoutRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  DoctorsDoctorIdBookingRoute: DoctorsDoctorIdBookingRoute,
  DoctorsDoctorIdDetailsRoute: DoctorsDoctorIdDetailsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
