/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuccessPageRouteImport } from './routes/success-page'
import { Route as PaymentDetailsRouteImport } from './routes/payment-details'
import { Route as MyBookingRouteImport } from './routes/my-booking'
import { Route as FutureAppointmentSuccesRouteImport } from './routes/future-appointment-succes'
import { Route as FutureAppointmentPendingRouteImport } from './routes/future-appointment-pending'
import { Route as LayoutPublicBlankRouteImport } from './routes/_layout-public-blank'
import { Route as LayoutDashboardRouteImport } from './routes/_layout-dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as LayoutDashboardDashboardRouteImport } from './routes/_layout-dashboard/dashboard'
import { Route as LayoutPublicBlankDoctorsSearchRouteImport } from './routes/_layout-public-blank/doctors.search'
import { Route as LayoutPublicBlankDoctorsDoctorIdDetailsRouteImport } from './routes/_layout-public-blank/doctors.$doctorId.details'
import { Route as LayoutPublicBlankDoctorsDoctorIdBookingRouteImport } from './routes/_layout-public-blank/doctors.$doctorId.booking'

const SuccessPageRoute = SuccessPageRouteImport.update({
  id: '/success-page',
  path: '/success-page',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentDetailsRoute = PaymentDetailsRouteImport.update({
  id: '/payment-details',
  path: '/payment-details',
  getParentRoute: () => rootRouteImport,
} as any)
const MyBookingRoute = MyBookingRouteImport.update({
  id: '/my-booking',
  path: '/my-booking',
  getParentRoute: () => rootRouteImport,
} as any)
const FutureAppointmentSuccesRoute = FutureAppointmentSuccesRouteImport.update({
  id: '/future-appointment-succes',
  path: '/future-appointment-succes',
  getParentRoute: () => rootRouteImport,
} as any)
const FutureAppointmentPendingRoute =
  FutureAppointmentPendingRouteImport.update({
    id: '/future-appointment-pending',
    path: '/future-appointment-pending',
    getParentRoute: () => rootRouteImport,
  } as any)
const LayoutPublicBlankRoute = LayoutPublicBlankRouteImport.update({
  id: '/_layout-public-blank',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutDashboardRoute = LayoutDashboardRouteImport.update({
  id: '/_layout-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutDashboardDashboardRoute =
  LayoutDashboardDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => LayoutDashboardRoute,
  } as any)
const LayoutPublicBlankDoctorsSearchRoute =
  LayoutPublicBlankDoctorsSearchRouteImport.update({
    id: '/doctors/search',
    path: '/doctors/search',
    getParentRoute: () => LayoutPublicBlankRoute,
  } as any)
const LayoutPublicBlankDoctorsDoctorIdDetailsRoute =
  LayoutPublicBlankDoctorsDoctorIdDetailsRouteImport.update({
    id: '/doctors/$doctorId/details',
    path: '/doctors/$doctorId/details',
    getParentRoute: () => LayoutPublicBlankRoute,
  } as any)
const LayoutPublicBlankDoctorsDoctorIdBookingRoute =
  LayoutPublicBlankDoctorsDoctorIdBookingRouteImport.update({
    id: '/doctors/$doctorId/booking',
    path: '/doctors/$doctorId/booking',
    getParentRoute: () => LayoutPublicBlankRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/future-appointment-pending': typeof FutureAppointmentPendingRoute
  '/future-appointment-succes': typeof FutureAppointmentSuccesRoute
  '/my-booking': typeof MyBookingRoute
  '/payment-details': typeof PaymentDetailsRoute
  '/success-page': typeof SuccessPageRoute
  '/dashboard': typeof LayoutDashboardDashboardRoute
  '/auth/login': typeof AuthLoginRoute
  '/doctors/search': typeof LayoutPublicBlankDoctorsSearchRoute
  '/doctors/$doctorId/booking': typeof LayoutPublicBlankDoctorsDoctorIdBookingRoute
  '/doctors/$doctorId/details': typeof LayoutPublicBlankDoctorsDoctorIdDetailsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/future-appointment-pending': typeof FutureAppointmentPendingRoute
  '/future-appointment-succes': typeof FutureAppointmentSuccesRoute
  '/my-booking': typeof MyBookingRoute
  '/payment-details': typeof PaymentDetailsRoute
  '/success-page': typeof SuccessPageRoute
  '/dashboard': typeof LayoutDashboardDashboardRoute
  '/auth/login': typeof AuthLoginRoute
  '/doctors/search': typeof LayoutPublicBlankDoctorsSearchRoute
  '/doctors/$doctorId/booking': typeof LayoutPublicBlankDoctorsDoctorIdBookingRoute
  '/doctors/$doctorId/details': typeof LayoutPublicBlankDoctorsDoctorIdDetailsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout-dashboard': typeof LayoutDashboardRouteWithChildren
  '/_layout-public-blank': typeof LayoutPublicBlankRouteWithChildren
  '/future-appointment-pending': typeof FutureAppointmentPendingRoute
  '/future-appointment-succes': typeof FutureAppointmentSuccesRoute
  '/my-booking': typeof MyBookingRoute
  '/payment-details': typeof PaymentDetailsRoute
  '/success-page': typeof SuccessPageRoute
  '/_layout-dashboard/dashboard': typeof LayoutDashboardDashboardRoute
  '/auth/login': typeof AuthLoginRoute
  '/_layout-public-blank/doctors/search': typeof LayoutPublicBlankDoctorsSearchRoute
  '/_layout-public-blank/doctors/$doctorId/booking': typeof LayoutPublicBlankDoctorsDoctorIdBookingRoute
  '/_layout-public-blank/doctors/$doctorId/details': typeof LayoutPublicBlankDoctorsDoctorIdDetailsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/future-appointment-pending'
    | '/future-appointment-succes'
    | '/my-booking'
    | '/payment-details'
    | '/success-page'
    | '/dashboard'
    | '/auth/login'
    | '/doctors/search'
    | '/doctors/$doctorId/booking'
    | '/doctors/$doctorId/details'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/future-appointment-pending'
    | '/future-appointment-succes'
    | '/my-booking'
    | '/payment-details'
    | '/success-page'
    | '/dashboard'
    | '/auth/login'
    | '/doctors/search'
    | '/doctors/$doctorId/booking'
    | '/doctors/$doctorId/details'
  id:
    | '__root__'
    | '/'
    | '/_layout-dashboard'
    | '/_layout-public-blank'
    | '/future-appointment-pending'
    | '/future-appointment-succes'
    | '/my-booking'
    | '/payment-details'
    | '/success-page'
    | '/_layout-dashboard/dashboard'
    | '/auth/login'
    | '/_layout-public-blank/doctors/search'
    | '/_layout-public-blank/doctors/$doctorId/booking'
    | '/_layout-public-blank/doctors/$doctorId/details'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutDashboardRoute: typeof LayoutDashboardRouteWithChildren
  LayoutPublicBlankRoute: typeof LayoutPublicBlankRouteWithChildren
  FutureAppointmentPendingRoute: typeof FutureAppointmentPendingRoute
  FutureAppointmentSuccesRoute: typeof FutureAppointmentSuccesRoute
  MyBookingRoute: typeof MyBookingRoute
  PaymentDetailsRoute: typeof PaymentDetailsRoute
  SuccessPageRoute: typeof SuccessPageRoute
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/success-page': {
      id: '/success-page'
      path: '/success-page'
      fullPath: '/success-page'
      preLoaderRoute: typeof SuccessPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-details': {
      id: '/payment-details'
      path: '/payment-details'
      fullPath: '/payment-details'
      preLoaderRoute: typeof PaymentDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-booking': {
      id: '/my-booking'
      path: '/my-booking'
      fullPath: '/my-booking'
      preLoaderRoute: typeof MyBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/future-appointment-succes': {
      id: '/future-appointment-succes'
      path: '/future-appointment-succes'
      fullPath: '/future-appointment-succes'
      preLoaderRoute: typeof FutureAppointmentSuccesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/future-appointment-pending': {
      id: '/future-appointment-pending'
      path: '/future-appointment-pending'
      fullPath: '/future-appointment-pending'
      preLoaderRoute: typeof FutureAppointmentPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout-public-blank': {
      id: '/_layout-public-blank'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutPublicBlankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout-dashboard': {
      id: '/_layout-dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout-dashboard/dashboard': {
      id: '/_layout-dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardDashboardRouteImport
      parentRoute: typeof LayoutDashboardRoute
    }
    '/_layout-public-blank/doctors/search': {
      id: '/_layout-public-blank/doctors/search'
      path: '/doctors/search'
      fullPath: '/doctors/search'
      preLoaderRoute: typeof LayoutPublicBlankDoctorsSearchRouteImport
      parentRoute: typeof LayoutPublicBlankRoute
    }
    '/_layout-public-blank/doctors/$doctorId/details': {
      id: '/_layout-public-blank/doctors/$doctorId/details'
      path: '/doctors/$doctorId/details'
      fullPath: '/doctors/$doctorId/details'
      preLoaderRoute: typeof LayoutPublicBlankDoctorsDoctorIdDetailsRouteImport
      parentRoute: typeof LayoutPublicBlankRoute
    }
    '/_layout-public-blank/doctors/$doctorId/booking': {
      id: '/_layout-public-blank/doctors/$doctorId/booking'
      path: '/doctors/$doctorId/booking'
      fullPath: '/doctors/$doctorId/booking'
      preLoaderRoute: typeof LayoutPublicBlankDoctorsDoctorIdBookingRouteImport
      parentRoute: typeof LayoutPublicBlankRoute
    }
  }
}

interface LayoutDashboardRouteChildren {
  LayoutDashboardDashboardRoute: typeof LayoutDashboardDashboardRoute
}

const LayoutDashboardRouteChildren: LayoutDashboardRouteChildren = {
  LayoutDashboardDashboardRoute: LayoutDashboardDashboardRoute,
}

const LayoutDashboardRouteWithChildren = LayoutDashboardRoute._addFileChildren(
  LayoutDashboardRouteChildren,
)

interface LayoutPublicBlankRouteChildren {
  LayoutPublicBlankDoctorsSearchRoute: typeof LayoutPublicBlankDoctorsSearchRoute
  LayoutPublicBlankDoctorsDoctorIdBookingRoute: typeof LayoutPublicBlankDoctorsDoctorIdBookingRoute
  LayoutPublicBlankDoctorsDoctorIdDetailsRoute: typeof LayoutPublicBlankDoctorsDoctorIdDetailsRoute
}

const LayoutPublicBlankRouteChildren: LayoutPublicBlankRouteChildren = {
  LayoutPublicBlankDoctorsSearchRoute: LayoutPublicBlankDoctorsSearchRoute,
  LayoutPublicBlankDoctorsDoctorIdBookingRoute:
    LayoutPublicBlankDoctorsDoctorIdBookingRoute,
  LayoutPublicBlankDoctorsDoctorIdDetailsRoute:
    LayoutPublicBlankDoctorsDoctorIdDetailsRoute,
}

const LayoutPublicBlankRouteWithChildren =
  LayoutPublicBlankRoute._addFileChildren(LayoutPublicBlankRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutDashboardRoute: LayoutDashboardRouteWithChildren,
  LayoutPublicBlankRoute: LayoutPublicBlankRouteWithChildren,
  FutureAppointmentPendingRoute: FutureAppointmentPendingRoute,
  FutureAppointmentSuccesRoute: FutureAppointmentSuccesRoute,
  MyBookingRoute: MyBookingRoute,
  PaymentDetailsRoute: PaymentDetailsRoute,
  SuccessPageRoute: SuccessPageRoute,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
