/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotFoundRouteImport } from './routes/not-found'
import { Route as LayoutPublicNavRouteImport } from './routes/_layout-public-nav'
import { Route as LayoutPublicBlankRouteImport } from './routes/_layout-public-blank'
import { Route as LayoutDashboardRouteImport } from './routes/_layout-dashboard'
import { Route as LayoutBlankRouteImport } from './routes/_layout-blank'
import { Route as LayoutPublicNavIndexRouteImport } from './routes/_layout-public-nav/index'
import { Route as LayoutPublicNavProfileRouteImport } from './routes/_layout-public-nav/profile'
import { Route as LayoutPublicNavAppointmentsRouteImport } from './routes/_layout-public-nav/appointments'
import { Route as LayoutDashboardDashboardRouteImport } from './routes/_layout-dashboard/dashboard'
import { Route as LayoutBlankAuthRouteImport } from './routes/_layout-blank/auth'
import { Route as LayoutPublicNavProfileIndexRouteImport } from './routes/_layout-public-nav/profile/index'
import { Route as LayoutPublicNavProfileEditRouteImport } from './routes/_layout-public-nav/profile/edit'
import { Route as LayoutPublicNavDoctorsSearchRouteImport } from './routes/_layout-public-nav/doctors.search'
import { Route as LayoutPublicBlankDoctorsResultsRouteImport } from './routes/_layout-public-blank/doctors.results'
import { Route as LayoutBlankAuthRegisterRouteImport } from './routes/_layout-blank/auth.register'
import { Route as LayoutBlankAuthLoginRouteImport } from './routes/_layout-blank/auth.login'
import { Route as LayoutDashboardAppUsersIndexRouteImport } from './routes/_layout-dashboard/app.users/index'
import { Route as LayoutDashboardAppSpecialistsIndexRouteImport } from './routes/_layout-dashboard/app.specialists/index'
import { Route as LayoutDashboardAppPatientsIndexRouteImport } from './routes/_layout-dashboard/app.patients/index'
import { Route as LayoutDashboardAppDoctorsIndexRouteImport } from './routes/_layout-dashboard/app.doctors/index'
import { Route as LayoutDashboardAppAppointmentsIndexRouteImport } from './routes/_layout-dashboard/app.appointments/index'
import { Route as LayoutPublicBlankDoctorsDoctorIdDetailsRouteImport } from './routes/_layout-public-blank/doctors.$doctorId.details'
import { Route as LayoutPublicBlankDoctorsDoctorIdBookingRouteImport } from './routes/_layout-public-blank/doctors.$doctorId.booking'
import { Route as LayoutPublicBlankAppointmentsAppointmentIdSuccessRouteImport } from './routes/_layout-public-blank/appointments.$appointmentId.success'
import { Route as LayoutPublicBlankAppointmentsAppointmentIdDetailsRouteImport } from './routes/_layout-public-blank/appointments.$appointmentId.details'
import { Route as LayoutDashboardSettingsDoctorsScheduleRouteImport } from './routes/_layout-dashboard/settings.doctors/schedule'
import { Route as LayoutDashboardAppUsersCreateRouteImport } from './routes/_layout-dashboard/app.users/create'
import { Route as LayoutDashboardAppSpecialistsCreateRouteImport } from './routes/_layout-dashboard/app.specialists/create'
import { Route as LayoutDashboardAppDoctorsCreateRouteImport } from './routes/_layout-dashboard/app.doctors/create'
import { Route as LayoutDashboardAppUsersUserIdEditRouteImport } from './routes/_layout-dashboard/app.users/$userId.edit'
import { Route as LayoutDashboardAppSpecialistsSpecialistIdEditRouteImport } from './routes/_layout-dashboard/app.specialists/$specialistId.edit'
import { Route as LayoutDashboardAppPatientsPatientIdEditRouteImport } from './routes/_layout-dashboard/app.patients/$patientId.edit'
import { Route as LayoutDashboardAppDoctorsDoctorIdEditRouteImport } from './routes/_layout-dashboard/app.doctors/$doctorId.edit'

const NotFoundRoute = NotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutPublicNavRoute = LayoutPublicNavRouteImport.update({
  id: '/_layout-public-nav',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutPublicBlankRoute = LayoutPublicBlankRouteImport.update({
  id: '/_layout-public-blank',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutDashboardRoute = LayoutDashboardRouteImport.update({
  id: '/_layout-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutBlankRoute = LayoutBlankRouteImport.update({
  id: '/_layout-blank',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutPublicNavIndexRoute = LayoutPublicNavIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutPublicNavRoute,
} as any)
const LayoutPublicNavProfileRoute = LayoutPublicNavProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => LayoutPublicNavRoute,
} as any)
const LayoutPublicNavAppointmentsRoute =
  LayoutPublicNavAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => LayoutPublicNavRoute,
  } as any)
const LayoutDashboardDashboardRoute =
  LayoutDashboardDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => LayoutDashboardRoute,
  } as any)
const LayoutBlankAuthRoute = LayoutBlankAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => LayoutBlankRoute,
} as any)
const LayoutPublicNavProfileIndexRoute =
  LayoutPublicNavProfileIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutPublicNavProfileRoute,
  } as any)
const LayoutPublicNavProfileEditRoute =
  LayoutPublicNavProfileEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => LayoutPublicNavProfileRoute,
  } as any)
const LayoutPublicNavDoctorsSearchRoute =
  LayoutPublicNavDoctorsSearchRouteImport.update({
    id: '/doctors/search',
    path: '/doctors/search',
    getParentRoute: () => LayoutPublicNavRoute,
  } as any)
const LayoutPublicBlankDoctorsResultsRoute =
  LayoutPublicBlankDoctorsResultsRouteImport.update({
    id: '/doctors/results',
    path: '/doctors/results',
    getParentRoute: () => LayoutPublicBlankRoute,
  } as any)
const LayoutBlankAuthRegisterRoute = LayoutBlankAuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => LayoutBlankAuthRoute,
} as any)
const LayoutBlankAuthLoginRoute = LayoutBlankAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LayoutBlankAuthRoute,
} as any)
const LayoutDashboardAppUsersIndexRoute =
  LayoutDashboardAppUsersIndexRouteImport.update({
    id: '/app/users/',
    path: '/app/users/',
    getParentRoute: () => LayoutDashboardRoute,
  } as any)
const LayoutDashboardAppSpecialistsIndexRoute =
  LayoutDashboardAppSpecialistsIndexRouteImport.update({
    id: '/app/specialists/',
    path: '/app/specialists/',
    getParentRoute: () => LayoutDashboardRoute,
  } as any)
const LayoutDashboardAppPatientsIndexRoute =
  LayoutDashboardAppPatientsIndexRouteImport.update({
    id: '/app/patients/',
    path: '/app/patients/',
    getParentRoute: () => LayoutDashboardRoute,
  } as any)
const LayoutDashboardAppDoctorsIndexRoute =
  LayoutDashboardAppDoctorsIndexRouteImport.update({
    id: '/app/doctors/',
    path: '/app/doctors/',
    getParentRoute: () => LayoutDashboardRoute,
  } as any)
const LayoutDashboardAppAppointmentsIndexRoute =
  LayoutDashboardAppAppointmentsIndexRouteImport.update({
    id: '/app/appointments/',
    path: '/app/appointments/',
    getParentRoute: () => LayoutDashboardRoute,
  } as any)
const LayoutPublicBlankDoctorsDoctorIdDetailsRoute =
  LayoutPublicBlankDoctorsDoctorIdDetailsRouteImport.update({
    id: '/doctors/$doctorId/details',
    path: '/doctors/$doctorId/details',
    getParentRoute: () => LayoutPublicBlankRoute,
  } as any)
const LayoutPublicBlankDoctorsDoctorIdBookingRoute =
  LayoutPublicBlankDoctorsDoctorIdBookingRouteImport.update({
    id: '/doctors/$doctorId/booking',
    path: '/doctors/$doctorId/booking',
    getParentRoute: () => LayoutPublicBlankRoute,
  } as any)
const LayoutPublicBlankAppointmentsAppointmentIdSuccessRoute =
  LayoutPublicBlankAppointmentsAppointmentIdSuccessRouteImport.update({
    id: '/appointments/$appointmentId/success',
    path: '/appointments/$appointmentId/success',
    getParentRoute: () => LayoutPublicBlankRoute,
  } as any)
const LayoutPublicBlankAppointmentsAppointmentIdDetailsRoute =
  LayoutPublicBlankAppointmentsAppointmentIdDetailsRouteImport.update({
    id: '/appointments/$appointmentId/details',
    path: '/appointments/$appointmentId/details',
    getParentRoute: () => LayoutPublicBlankRoute,
  } as any)
const LayoutDashboardSettingsDoctorsScheduleRoute =
  LayoutDashboardSettingsDoctorsScheduleRouteImport.update({
    id: '/settings/doctors/schedule',
    path: '/settings/doctors/schedule',
    getParentRoute: () => LayoutDashboardRoute,
  } as any)
const LayoutDashboardAppUsersCreateRoute =
  LayoutDashboardAppUsersCreateRouteImport.update({
    id: '/app/users/create',
    path: '/app/users/create',
    getParentRoute: () => LayoutDashboardRoute,
  } as any)
const LayoutDashboardAppSpecialistsCreateRoute =
  LayoutDashboardAppSpecialistsCreateRouteImport.update({
    id: '/app/specialists/create',
    path: '/app/specialists/create',
    getParentRoute: () => LayoutDashboardRoute,
  } as any)
const LayoutDashboardAppDoctorsCreateRoute =
  LayoutDashboardAppDoctorsCreateRouteImport.update({
    id: '/app/doctors/create',
    path: '/app/doctors/create',
    getParentRoute: () => LayoutDashboardRoute,
  } as any)
const LayoutDashboardAppUsersUserIdEditRoute =
  LayoutDashboardAppUsersUserIdEditRouteImport.update({
    id: '/app/users/$userId/edit',
    path: '/app/users/$userId/edit',
    getParentRoute: () => LayoutDashboardRoute,
  } as any)
const LayoutDashboardAppSpecialistsSpecialistIdEditRoute =
  LayoutDashboardAppSpecialistsSpecialistIdEditRouteImport.update({
    id: '/app/specialists/$specialistId/edit',
    path: '/app/specialists/$specialistId/edit',
    getParentRoute: () => LayoutDashboardRoute,
  } as any)
const LayoutDashboardAppPatientsPatientIdEditRoute =
  LayoutDashboardAppPatientsPatientIdEditRouteImport.update({
    id: '/app/patients/$patientId/edit',
    path: '/app/patients/$patientId/edit',
    getParentRoute: () => LayoutDashboardRoute,
  } as any)
const LayoutDashboardAppDoctorsDoctorIdEditRoute =
  LayoutDashboardAppDoctorsDoctorIdEditRouteImport.update({
    id: '/app/doctors/$doctorId/edit',
    path: '/app/doctors/$doctorId/edit',
    getParentRoute: () => LayoutDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutPublicNavIndexRoute
  '/not-found': typeof NotFoundRoute
  '/auth': typeof LayoutBlankAuthRouteWithChildren
  '/dashboard': typeof LayoutDashboardDashboardRoute
  '/appointments': typeof LayoutPublicNavAppointmentsRoute
  '/profile': typeof LayoutPublicNavProfileRouteWithChildren
  '/auth/login': typeof LayoutBlankAuthLoginRoute
  '/auth/register': typeof LayoutBlankAuthRegisterRoute
  '/doctors/results': typeof LayoutPublicBlankDoctorsResultsRoute
  '/doctors/search': typeof LayoutPublicNavDoctorsSearchRoute
  '/profile/edit': typeof LayoutPublicNavProfileEditRoute
  '/profile/': typeof LayoutPublicNavProfileIndexRoute
  '/app/doctors/create': typeof LayoutDashboardAppDoctorsCreateRoute
  '/app/specialists/create': typeof LayoutDashboardAppSpecialistsCreateRoute
  '/app/users/create': typeof LayoutDashboardAppUsersCreateRoute
  '/settings/doctors/schedule': typeof LayoutDashboardSettingsDoctorsScheduleRoute
  '/appointments/$appointmentId/details': typeof LayoutPublicBlankAppointmentsAppointmentIdDetailsRoute
  '/appointments/$appointmentId/success': typeof LayoutPublicBlankAppointmentsAppointmentIdSuccessRoute
  '/doctors/$doctorId/booking': typeof LayoutPublicBlankDoctorsDoctorIdBookingRoute
  '/doctors/$doctorId/details': typeof LayoutPublicBlankDoctorsDoctorIdDetailsRoute
  '/app/appointments/': typeof LayoutDashboardAppAppointmentsIndexRoute
  '/app/doctors/': typeof LayoutDashboardAppDoctorsIndexRoute
  '/app/patients/': typeof LayoutDashboardAppPatientsIndexRoute
  '/app/specialists/': typeof LayoutDashboardAppSpecialistsIndexRoute
  '/app/users/': typeof LayoutDashboardAppUsersIndexRoute
  '/app/doctors/$doctorId/edit': typeof LayoutDashboardAppDoctorsDoctorIdEditRoute
  '/app/patients/$patientId/edit': typeof LayoutDashboardAppPatientsPatientIdEditRoute
  '/app/specialists/$specialistId/edit': typeof LayoutDashboardAppSpecialistsSpecialistIdEditRoute
  '/app/users/$userId/edit': typeof LayoutDashboardAppUsersUserIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof LayoutPublicNavIndexRoute
  '/not-found': typeof NotFoundRoute
  '/auth': typeof LayoutBlankAuthRouteWithChildren
  '/dashboard': typeof LayoutDashboardDashboardRoute
  '/appointments': typeof LayoutPublicNavAppointmentsRoute
  '/auth/login': typeof LayoutBlankAuthLoginRoute
  '/auth/register': typeof LayoutBlankAuthRegisterRoute
  '/doctors/results': typeof LayoutPublicBlankDoctorsResultsRoute
  '/doctors/search': typeof LayoutPublicNavDoctorsSearchRoute
  '/profile/edit': typeof LayoutPublicNavProfileEditRoute
  '/profile': typeof LayoutPublicNavProfileIndexRoute
  '/app/doctors/create': typeof LayoutDashboardAppDoctorsCreateRoute
  '/app/specialists/create': typeof LayoutDashboardAppSpecialistsCreateRoute
  '/app/users/create': typeof LayoutDashboardAppUsersCreateRoute
  '/settings/doctors/schedule': typeof LayoutDashboardSettingsDoctorsScheduleRoute
  '/appointments/$appointmentId/details': typeof LayoutPublicBlankAppointmentsAppointmentIdDetailsRoute
  '/appointments/$appointmentId/success': typeof LayoutPublicBlankAppointmentsAppointmentIdSuccessRoute
  '/doctors/$doctorId/booking': typeof LayoutPublicBlankDoctorsDoctorIdBookingRoute
  '/doctors/$doctorId/details': typeof LayoutPublicBlankDoctorsDoctorIdDetailsRoute
  '/app/appointments': typeof LayoutDashboardAppAppointmentsIndexRoute
  '/app/doctors': typeof LayoutDashboardAppDoctorsIndexRoute
  '/app/patients': typeof LayoutDashboardAppPatientsIndexRoute
  '/app/specialists': typeof LayoutDashboardAppSpecialistsIndexRoute
  '/app/users': typeof LayoutDashboardAppUsersIndexRoute
  '/app/doctors/$doctorId/edit': typeof LayoutDashboardAppDoctorsDoctorIdEditRoute
  '/app/patients/$patientId/edit': typeof LayoutDashboardAppPatientsPatientIdEditRoute
  '/app/specialists/$specialistId/edit': typeof LayoutDashboardAppSpecialistsSpecialistIdEditRoute
  '/app/users/$userId/edit': typeof LayoutDashboardAppUsersUserIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout-blank': typeof LayoutBlankRouteWithChildren
  '/_layout-dashboard': typeof LayoutDashboardRouteWithChildren
  '/_layout-public-blank': typeof LayoutPublicBlankRouteWithChildren
  '/_layout-public-nav': typeof LayoutPublicNavRouteWithChildren
  '/not-found': typeof NotFoundRoute
  '/_layout-blank/auth': typeof LayoutBlankAuthRouteWithChildren
  '/_layout-dashboard/dashboard': typeof LayoutDashboardDashboardRoute
  '/_layout-public-nav/appointments': typeof LayoutPublicNavAppointmentsRoute
  '/_layout-public-nav/profile': typeof LayoutPublicNavProfileRouteWithChildren
  '/_layout-public-nav/': typeof LayoutPublicNavIndexRoute
  '/_layout-blank/auth/login': typeof LayoutBlankAuthLoginRoute
  '/_layout-blank/auth/register': typeof LayoutBlankAuthRegisterRoute
  '/_layout-public-blank/doctors/results': typeof LayoutPublicBlankDoctorsResultsRoute
  '/_layout-public-nav/doctors/search': typeof LayoutPublicNavDoctorsSearchRoute
  '/_layout-public-nav/profile/edit': typeof LayoutPublicNavProfileEditRoute
  '/_layout-public-nav/profile/': typeof LayoutPublicNavProfileIndexRoute
  '/_layout-dashboard/app/doctors/create': typeof LayoutDashboardAppDoctorsCreateRoute
  '/_layout-dashboard/app/specialists/create': typeof LayoutDashboardAppSpecialistsCreateRoute
  '/_layout-dashboard/app/users/create': typeof LayoutDashboardAppUsersCreateRoute
  '/_layout-dashboard/settings/doctors/schedule': typeof LayoutDashboardSettingsDoctorsScheduleRoute
  '/_layout-public-blank/appointments/$appointmentId/details': typeof LayoutPublicBlankAppointmentsAppointmentIdDetailsRoute
  '/_layout-public-blank/appointments/$appointmentId/success': typeof LayoutPublicBlankAppointmentsAppointmentIdSuccessRoute
  '/_layout-public-blank/doctors/$doctorId/booking': typeof LayoutPublicBlankDoctorsDoctorIdBookingRoute
  '/_layout-public-blank/doctors/$doctorId/details': typeof LayoutPublicBlankDoctorsDoctorIdDetailsRoute
  '/_layout-dashboard/app/appointments/': typeof LayoutDashboardAppAppointmentsIndexRoute
  '/_layout-dashboard/app/doctors/': typeof LayoutDashboardAppDoctorsIndexRoute
  '/_layout-dashboard/app/patients/': typeof LayoutDashboardAppPatientsIndexRoute
  '/_layout-dashboard/app/specialists/': typeof LayoutDashboardAppSpecialistsIndexRoute
  '/_layout-dashboard/app/users/': typeof LayoutDashboardAppUsersIndexRoute
  '/_layout-dashboard/app/doctors/$doctorId/edit': typeof LayoutDashboardAppDoctorsDoctorIdEditRoute
  '/_layout-dashboard/app/patients/$patientId/edit': typeof LayoutDashboardAppPatientsPatientIdEditRoute
  '/_layout-dashboard/app/specialists/$specialistId/edit': typeof LayoutDashboardAppSpecialistsSpecialistIdEditRoute
  '/_layout-dashboard/app/users/$userId/edit': typeof LayoutDashboardAppUsersUserIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/not-found'
    | '/auth'
    | '/dashboard'
    | '/appointments'
    | '/profile'
    | '/auth/login'
    | '/auth/register'
    | '/doctors/results'
    | '/doctors/search'
    | '/profile/edit'
    | '/profile/'
    | '/app/doctors/create'
    | '/app/specialists/create'
    | '/app/users/create'
    | '/settings/doctors/schedule'
    | '/appointments/$appointmentId/details'
    | '/appointments/$appointmentId/success'
    | '/doctors/$doctorId/booking'
    | '/doctors/$doctorId/details'
    | '/app/appointments/'
    | '/app/doctors/'
    | '/app/patients/'
    | '/app/specialists/'
    | '/app/users/'
    | '/app/doctors/$doctorId/edit'
    | '/app/patients/$patientId/edit'
    | '/app/specialists/$specialistId/edit'
    | '/app/users/$userId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/not-found'
    | '/auth'
    | '/dashboard'
    | '/appointments'
    | '/auth/login'
    | '/auth/register'
    | '/doctors/results'
    | '/doctors/search'
    | '/profile/edit'
    | '/profile'
    | '/app/doctors/create'
    | '/app/specialists/create'
    | '/app/users/create'
    | '/settings/doctors/schedule'
    | '/appointments/$appointmentId/details'
    | '/appointments/$appointmentId/success'
    | '/doctors/$doctorId/booking'
    | '/doctors/$doctorId/details'
    | '/app/appointments'
    | '/app/doctors'
    | '/app/patients'
    | '/app/specialists'
    | '/app/users'
    | '/app/doctors/$doctorId/edit'
    | '/app/patients/$patientId/edit'
    | '/app/specialists/$specialistId/edit'
    | '/app/users/$userId/edit'
  id:
    | '__root__'
    | '/_layout-blank'
    | '/_layout-dashboard'
    | '/_layout-public-blank'
    | '/_layout-public-nav'
    | '/not-found'
    | '/_layout-blank/auth'
    | '/_layout-dashboard/dashboard'
    | '/_layout-public-nav/appointments'
    | '/_layout-public-nav/profile'
    | '/_layout-public-nav/'
    | '/_layout-blank/auth/login'
    | '/_layout-blank/auth/register'
    | '/_layout-public-blank/doctors/results'
    | '/_layout-public-nav/doctors/search'
    | '/_layout-public-nav/profile/edit'
    | '/_layout-public-nav/profile/'
    | '/_layout-dashboard/app/doctors/create'
    | '/_layout-dashboard/app/specialists/create'
    | '/_layout-dashboard/app/users/create'
    | '/_layout-dashboard/settings/doctors/schedule'
    | '/_layout-public-blank/appointments/$appointmentId/details'
    | '/_layout-public-blank/appointments/$appointmentId/success'
    | '/_layout-public-blank/doctors/$doctorId/booking'
    | '/_layout-public-blank/doctors/$doctorId/details'
    | '/_layout-dashboard/app/appointments/'
    | '/_layout-dashboard/app/doctors/'
    | '/_layout-dashboard/app/patients/'
    | '/_layout-dashboard/app/specialists/'
    | '/_layout-dashboard/app/users/'
    | '/_layout-dashboard/app/doctors/$doctorId/edit'
    | '/_layout-dashboard/app/patients/$patientId/edit'
    | '/_layout-dashboard/app/specialists/$specialistId/edit'
    | '/_layout-dashboard/app/users/$userId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutBlankRoute: typeof LayoutBlankRouteWithChildren
  LayoutDashboardRoute: typeof LayoutDashboardRouteWithChildren
  LayoutPublicBlankRoute: typeof LayoutPublicBlankRouteWithChildren
  LayoutPublicNavRoute: typeof LayoutPublicNavRouteWithChildren
  NotFoundRoute: typeof NotFoundRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout-public-nav': {
      id: '/_layout-public-nav'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutPublicNavRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout-public-blank': {
      id: '/_layout-public-blank'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutPublicBlankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout-dashboard': {
      id: '/_layout-dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout-blank': {
      id: '/_layout-blank'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutBlankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout-public-nav/': {
      id: '/_layout-public-nav/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutPublicNavIndexRouteImport
      parentRoute: typeof LayoutPublicNavRoute
    }
    '/_layout-public-nav/profile': {
      id: '/_layout-public-nav/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof LayoutPublicNavProfileRouteImport
      parentRoute: typeof LayoutPublicNavRoute
    }
    '/_layout-public-nav/appointments': {
      id: '/_layout-public-nav/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof LayoutPublicNavAppointmentsRouteImport
      parentRoute: typeof LayoutPublicNavRoute
    }
    '/_layout-dashboard/dashboard': {
      id: '/_layout-dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardDashboardRouteImport
      parentRoute: typeof LayoutDashboardRoute
    }
    '/_layout-blank/auth': {
      id: '/_layout-blank/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof LayoutBlankAuthRouteImport
      parentRoute: typeof LayoutBlankRoute
    }
    '/_layout-public-nav/profile/': {
      id: '/_layout-public-nav/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof LayoutPublicNavProfileIndexRouteImport
      parentRoute: typeof LayoutPublicNavProfileRoute
    }
    '/_layout-public-nav/profile/edit': {
      id: '/_layout-public-nav/profile/edit'
      path: '/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof LayoutPublicNavProfileEditRouteImport
      parentRoute: typeof LayoutPublicNavProfileRoute
    }
    '/_layout-public-nav/doctors/search': {
      id: '/_layout-public-nav/doctors/search'
      path: '/doctors/search'
      fullPath: '/doctors/search'
      preLoaderRoute: typeof LayoutPublicNavDoctorsSearchRouteImport
      parentRoute: typeof LayoutPublicNavRoute
    }
    '/_layout-public-blank/doctors/results': {
      id: '/_layout-public-blank/doctors/results'
      path: '/doctors/results'
      fullPath: '/doctors/results'
      preLoaderRoute: typeof LayoutPublicBlankDoctorsResultsRouteImport
      parentRoute: typeof LayoutPublicBlankRoute
    }
    '/_layout-blank/auth/register': {
      id: '/_layout-blank/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof LayoutBlankAuthRegisterRouteImport
      parentRoute: typeof LayoutBlankAuthRoute
    }
    '/_layout-blank/auth/login': {
      id: '/_layout-blank/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof LayoutBlankAuthLoginRouteImport
      parentRoute: typeof LayoutBlankAuthRoute
    }
    '/_layout-dashboard/app/users/': {
      id: '/_layout-dashboard/app/users/'
      path: '/app/users'
      fullPath: '/app/users/'
      preLoaderRoute: typeof LayoutDashboardAppUsersIndexRouteImport
      parentRoute: typeof LayoutDashboardRoute
    }
    '/_layout-dashboard/app/specialists/': {
      id: '/_layout-dashboard/app/specialists/'
      path: '/app/specialists'
      fullPath: '/app/specialists/'
      preLoaderRoute: typeof LayoutDashboardAppSpecialistsIndexRouteImport
      parentRoute: typeof LayoutDashboardRoute
    }
    '/_layout-dashboard/app/patients/': {
      id: '/_layout-dashboard/app/patients/'
      path: '/app/patients'
      fullPath: '/app/patients/'
      preLoaderRoute: typeof LayoutDashboardAppPatientsIndexRouteImport
      parentRoute: typeof LayoutDashboardRoute
    }
    '/_layout-dashboard/app/doctors/': {
      id: '/_layout-dashboard/app/doctors/'
      path: '/app/doctors'
      fullPath: '/app/doctors/'
      preLoaderRoute: typeof LayoutDashboardAppDoctorsIndexRouteImport
      parentRoute: typeof LayoutDashboardRoute
    }
    '/_layout-dashboard/app/appointments/': {
      id: '/_layout-dashboard/app/appointments/'
      path: '/app/appointments'
      fullPath: '/app/appointments/'
      preLoaderRoute: typeof LayoutDashboardAppAppointmentsIndexRouteImport
      parentRoute: typeof LayoutDashboardRoute
    }
    '/_layout-public-blank/doctors/$doctorId/details': {
      id: '/_layout-public-blank/doctors/$doctorId/details'
      path: '/doctors/$doctorId/details'
      fullPath: '/doctors/$doctorId/details'
      preLoaderRoute: typeof LayoutPublicBlankDoctorsDoctorIdDetailsRouteImport
      parentRoute: typeof LayoutPublicBlankRoute
    }
    '/_layout-public-blank/doctors/$doctorId/booking': {
      id: '/_layout-public-blank/doctors/$doctorId/booking'
      path: '/doctors/$doctorId/booking'
      fullPath: '/doctors/$doctorId/booking'
      preLoaderRoute: typeof LayoutPublicBlankDoctorsDoctorIdBookingRouteImport
      parentRoute: typeof LayoutPublicBlankRoute
    }
    '/_layout-public-blank/appointments/$appointmentId/success': {
      id: '/_layout-public-blank/appointments/$appointmentId/success'
      path: '/appointments/$appointmentId/success'
      fullPath: '/appointments/$appointmentId/success'
      preLoaderRoute: typeof LayoutPublicBlankAppointmentsAppointmentIdSuccessRouteImport
      parentRoute: typeof LayoutPublicBlankRoute
    }
    '/_layout-public-blank/appointments/$appointmentId/details': {
      id: '/_layout-public-blank/appointments/$appointmentId/details'
      path: '/appointments/$appointmentId/details'
      fullPath: '/appointments/$appointmentId/details'
      preLoaderRoute: typeof LayoutPublicBlankAppointmentsAppointmentIdDetailsRouteImport
      parentRoute: typeof LayoutPublicBlankRoute
    }
    '/_layout-dashboard/settings/doctors/schedule': {
      id: '/_layout-dashboard/settings/doctors/schedule'
      path: '/settings/doctors/schedule'
      fullPath: '/settings/doctors/schedule'
      preLoaderRoute: typeof LayoutDashboardSettingsDoctorsScheduleRouteImport
      parentRoute: typeof LayoutDashboardRoute
    }
    '/_layout-dashboard/app/users/create': {
      id: '/_layout-dashboard/app/users/create'
      path: '/app/users/create'
      fullPath: '/app/users/create'
      preLoaderRoute: typeof LayoutDashboardAppUsersCreateRouteImport
      parentRoute: typeof LayoutDashboardRoute
    }
    '/_layout-dashboard/app/specialists/create': {
      id: '/_layout-dashboard/app/specialists/create'
      path: '/app/specialists/create'
      fullPath: '/app/specialists/create'
      preLoaderRoute: typeof LayoutDashboardAppSpecialistsCreateRouteImport
      parentRoute: typeof LayoutDashboardRoute
    }
    '/_layout-dashboard/app/doctors/create': {
      id: '/_layout-dashboard/app/doctors/create'
      path: '/app/doctors/create'
      fullPath: '/app/doctors/create'
      preLoaderRoute: typeof LayoutDashboardAppDoctorsCreateRouteImport
      parentRoute: typeof LayoutDashboardRoute
    }
    '/_layout-dashboard/app/users/$userId/edit': {
      id: '/_layout-dashboard/app/users/$userId/edit'
      path: '/app/users/$userId/edit'
      fullPath: '/app/users/$userId/edit'
      preLoaderRoute: typeof LayoutDashboardAppUsersUserIdEditRouteImport
      parentRoute: typeof LayoutDashboardRoute
    }
    '/_layout-dashboard/app/specialists/$specialistId/edit': {
      id: '/_layout-dashboard/app/specialists/$specialistId/edit'
      path: '/app/specialists/$specialistId/edit'
      fullPath: '/app/specialists/$specialistId/edit'
      preLoaderRoute: typeof LayoutDashboardAppSpecialistsSpecialistIdEditRouteImport
      parentRoute: typeof LayoutDashboardRoute
    }
    '/_layout-dashboard/app/patients/$patientId/edit': {
      id: '/_layout-dashboard/app/patients/$patientId/edit'
      path: '/app/patients/$patientId/edit'
      fullPath: '/app/patients/$patientId/edit'
      preLoaderRoute: typeof LayoutDashboardAppPatientsPatientIdEditRouteImport
      parentRoute: typeof LayoutDashboardRoute
    }
    '/_layout-dashboard/app/doctors/$doctorId/edit': {
      id: '/_layout-dashboard/app/doctors/$doctorId/edit'
      path: '/app/doctors/$doctorId/edit'
      fullPath: '/app/doctors/$doctorId/edit'
      preLoaderRoute: typeof LayoutDashboardAppDoctorsDoctorIdEditRouteImport
      parentRoute: typeof LayoutDashboardRoute
    }
  }
}

interface LayoutBlankAuthRouteChildren {
  LayoutBlankAuthLoginRoute: typeof LayoutBlankAuthLoginRoute
  LayoutBlankAuthRegisterRoute: typeof LayoutBlankAuthRegisterRoute
}

const LayoutBlankAuthRouteChildren: LayoutBlankAuthRouteChildren = {
  LayoutBlankAuthLoginRoute: LayoutBlankAuthLoginRoute,
  LayoutBlankAuthRegisterRoute: LayoutBlankAuthRegisterRoute,
}

const LayoutBlankAuthRouteWithChildren = LayoutBlankAuthRoute._addFileChildren(
  LayoutBlankAuthRouteChildren,
)

interface LayoutBlankRouteChildren {
  LayoutBlankAuthRoute: typeof LayoutBlankAuthRouteWithChildren
}

const LayoutBlankRouteChildren: LayoutBlankRouteChildren = {
  LayoutBlankAuthRoute: LayoutBlankAuthRouteWithChildren,
}

const LayoutBlankRouteWithChildren = LayoutBlankRoute._addFileChildren(
  LayoutBlankRouteChildren,
)

interface LayoutDashboardRouteChildren {
  LayoutDashboardDashboardRoute: typeof LayoutDashboardDashboardRoute
  LayoutDashboardAppDoctorsCreateRoute: typeof LayoutDashboardAppDoctorsCreateRoute
  LayoutDashboardAppSpecialistsCreateRoute: typeof LayoutDashboardAppSpecialistsCreateRoute
  LayoutDashboardAppUsersCreateRoute: typeof LayoutDashboardAppUsersCreateRoute
  LayoutDashboardSettingsDoctorsScheduleRoute: typeof LayoutDashboardSettingsDoctorsScheduleRoute
  LayoutDashboardAppAppointmentsIndexRoute: typeof LayoutDashboardAppAppointmentsIndexRoute
  LayoutDashboardAppDoctorsIndexRoute: typeof LayoutDashboardAppDoctorsIndexRoute
  LayoutDashboardAppPatientsIndexRoute: typeof LayoutDashboardAppPatientsIndexRoute
  LayoutDashboardAppSpecialistsIndexRoute: typeof LayoutDashboardAppSpecialistsIndexRoute
  LayoutDashboardAppUsersIndexRoute: typeof LayoutDashboardAppUsersIndexRoute
  LayoutDashboardAppDoctorsDoctorIdEditRoute: typeof LayoutDashboardAppDoctorsDoctorIdEditRoute
  LayoutDashboardAppPatientsPatientIdEditRoute: typeof LayoutDashboardAppPatientsPatientIdEditRoute
  LayoutDashboardAppSpecialistsSpecialistIdEditRoute: typeof LayoutDashboardAppSpecialistsSpecialistIdEditRoute
  LayoutDashboardAppUsersUserIdEditRoute: typeof LayoutDashboardAppUsersUserIdEditRoute
}

const LayoutDashboardRouteChildren: LayoutDashboardRouteChildren = {
  LayoutDashboardDashboardRoute: LayoutDashboardDashboardRoute,
  LayoutDashboardAppDoctorsCreateRoute: LayoutDashboardAppDoctorsCreateRoute,
  LayoutDashboardAppSpecialistsCreateRoute:
    LayoutDashboardAppSpecialistsCreateRoute,
  LayoutDashboardAppUsersCreateRoute: LayoutDashboardAppUsersCreateRoute,
  LayoutDashboardSettingsDoctorsScheduleRoute:
    LayoutDashboardSettingsDoctorsScheduleRoute,
  LayoutDashboardAppAppointmentsIndexRoute:
    LayoutDashboardAppAppointmentsIndexRoute,
  LayoutDashboardAppDoctorsIndexRoute: LayoutDashboardAppDoctorsIndexRoute,
  LayoutDashboardAppPatientsIndexRoute: LayoutDashboardAppPatientsIndexRoute,
  LayoutDashboardAppSpecialistsIndexRoute:
    LayoutDashboardAppSpecialistsIndexRoute,
  LayoutDashboardAppUsersIndexRoute: LayoutDashboardAppUsersIndexRoute,
  LayoutDashboardAppDoctorsDoctorIdEditRoute:
    LayoutDashboardAppDoctorsDoctorIdEditRoute,
  LayoutDashboardAppPatientsPatientIdEditRoute:
    LayoutDashboardAppPatientsPatientIdEditRoute,
  LayoutDashboardAppSpecialistsSpecialistIdEditRoute:
    LayoutDashboardAppSpecialistsSpecialistIdEditRoute,
  LayoutDashboardAppUsersUserIdEditRoute:
    LayoutDashboardAppUsersUserIdEditRoute,
}

const LayoutDashboardRouteWithChildren = LayoutDashboardRoute._addFileChildren(
  LayoutDashboardRouteChildren,
)

interface LayoutPublicBlankRouteChildren {
  LayoutPublicBlankDoctorsResultsRoute: typeof LayoutPublicBlankDoctorsResultsRoute
  LayoutPublicBlankAppointmentsAppointmentIdDetailsRoute: typeof LayoutPublicBlankAppointmentsAppointmentIdDetailsRoute
  LayoutPublicBlankAppointmentsAppointmentIdSuccessRoute: typeof LayoutPublicBlankAppointmentsAppointmentIdSuccessRoute
  LayoutPublicBlankDoctorsDoctorIdBookingRoute: typeof LayoutPublicBlankDoctorsDoctorIdBookingRoute
  LayoutPublicBlankDoctorsDoctorIdDetailsRoute: typeof LayoutPublicBlankDoctorsDoctorIdDetailsRoute
}

const LayoutPublicBlankRouteChildren: LayoutPublicBlankRouteChildren = {
  LayoutPublicBlankDoctorsResultsRoute: LayoutPublicBlankDoctorsResultsRoute,
  LayoutPublicBlankAppointmentsAppointmentIdDetailsRoute:
    LayoutPublicBlankAppointmentsAppointmentIdDetailsRoute,
  LayoutPublicBlankAppointmentsAppointmentIdSuccessRoute:
    LayoutPublicBlankAppointmentsAppointmentIdSuccessRoute,
  LayoutPublicBlankDoctorsDoctorIdBookingRoute:
    LayoutPublicBlankDoctorsDoctorIdBookingRoute,
  LayoutPublicBlankDoctorsDoctorIdDetailsRoute:
    LayoutPublicBlankDoctorsDoctorIdDetailsRoute,
}

const LayoutPublicBlankRouteWithChildren =
  LayoutPublicBlankRoute._addFileChildren(LayoutPublicBlankRouteChildren)

interface LayoutPublicNavProfileRouteChildren {
  LayoutPublicNavProfileEditRoute: typeof LayoutPublicNavProfileEditRoute
  LayoutPublicNavProfileIndexRoute: typeof LayoutPublicNavProfileIndexRoute
}

const LayoutPublicNavProfileRouteChildren: LayoutPublicNavProfileRouteChildren =
  {
    LayoutPublicNavProfileEditRoute: LayoutPublicNavProfileEditRoute,
    LayoutPublicNavProfileIndexRoute: LayoutPublicNavProfileIndexRoute,
  }

const LayoutPublicNavProfileRouteWithChildren =
  LayoutPublicNavProfileRoute._addFileChildren(
    LayoutPublicNavProfileRouteChildren,
  )

interface LayoutPublicNavRouteChildren {
  LayoutPublicNavAppointmentsRoute: typeof LayoutPublicNavAppointmentsRoute
  LayoutPublicNavProfileRoute: typeof LayoutPublicNavProfileRouteWithChildren
  LayoutPublicNavIndexRoute: typeof LayoutPublicNavIndexRoute
  LayoutPublicNavDoctorsSearchRoute: typeof LayoutPublicNavDoctorsSearchRoute
}

const LayoutPublicNavRouteChildren: LayoutPublicNavRouteChildren = {
  LayoutPublicNavAppointmentsRoute: LayoutPublicNavAppointmentsRoute,
  LayoutPublicNavProfileRoute: LayoutPublicNavProfileRouteWithChildren,
  LayoutPublicNavIndexRoute: LayoutPublicNavIndexRoute,
  LayoutPublicNavDoctorsSearchRoute: LayoutPublicNavDoctorsSearchRoute,
}

const LayoutPublicNavRouteWithChildren = LayoutPublicNavRoute._addFileChildren(
  LayoutPublicNavRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LayoutBlankRoute: LayoutBlankRouteWithChildren,
  LayoutDashboardRoute: LayoutDashboardRouteWithChildren,
  LayoutPublicBlankRoute: LayoutPublicBlankRouteWithChildren,
  LayoutPublicNavRoute: LayoutPublicNavRouteWithChildren,
  NotFoundRoute: NotFoundRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
